---
title: "STAT 222 HW 1"
author: "Matthew Zhao"
output: pdf_document
---

```{r include=FALSE}
library(tidyverse)
```

## Problem 1
#### (a)
$\bar{y}_{\cdot\cdot} = \displaystyle \frac{1}{N} \sum_{i=1}^{g} n_i \bar{y}_{i\cdot} = \frac{1}{7+8+6+8} (7*3.7457 + 8*3.5800+6*3.5983+8*3.9225) = \frac{1}{29} * 107.8297 \approx 3.718266$


$SS_{trt} = \displaystyle \sum_{i=1}^g n_{i}(\bar{y}_{i\cdot} - \bar{y}_{\cdot\cdot})^{2} = 7*(3.7457 - 3.718266)^2 + 8*(3.5800 - 3.718266)^2 + 6*(3.5983 - 3.718266)^2 + 8*(3.9225 - 3.718266)^2 \approx 0.5782515$


#### (b)
$SSE = \displaystyle \sum_{i=1}^{g} (n_{i}-1)s_{i}^{2} = (7-1)*0.2840^{2} + (8-1)*0.1821^{2} + (6-1)*0.0962^{2} + (8-1)*0.1971^{2} \approx 1.03427$


#### (c)
Source    |  df  |  SS |  MS | F-stat
------------ | -------- | ----------- | ----------- |------- 
Treatment | $\text{df}_\text{trt}= 4-1 = 3$ | $\text{SS}_\text{trt}= 0.5782515$ | $\text{MS}_\text{trt} = \frac{\text{SS}_\text{trt}}{\text{df}_\text{trt}} = \frac{0.5782515}{3} \approx 0.1927505$ | $\text{F} = \frac{\text{MS}_\text{trt}}{\text{MSE}} = \frac{0.1927505}{0.0413708} \approx 4.659095$ 
Error     | $\text{df}_\text{E} = 29 - 4 = 25$ | $\text{SSE} = 1.03427$ |  $\text{MSE} = \frac{\text{SSE}}{N-g} = \frac{1.03427}{25} \approx 0.0413708$ | 

#### (d)
We run the code below to find the p value. 
```{r}
pf(4.659095,3,25, lower.tail = FALSE)
```
Since $0.05>p=0.01014922$, we can reject the null hypothesis that all the means are equal at the 95% confidence level, potentially indicating that the treament effects are statistically significant. 


## Problem 2
```{r}
rats = read.table("http://users.stat.umn.edu/~gary/book/fcdae.data/ex3.1", h=T)
anova(lm(y ~ diet, data = rats))
```

```{r}
anova(lm(y ~ as.factor(diet), data = rats))
```
## Problem 3
The 95% confidence interval for a group mean for group k is denoted $\bar{y}_{k\cdot} \pm t_{N-g,\frac{\alpha}{2}} * \frac{\sqrt{MSE}}{\sqrt{n_{k}}}$. Specifically, we can find $t_{N-g,\frac{\alpha}{2}}$ for the 95% confidence level and group $k=1$ using the R code below (where $N=29$, $g=4$, and $\frac{\alpha}{2} = 0.025$):
```{r}
qt(0.05/2,29-4,lower.tail = F)
```
Plugging the values back in, we can construct a confidence interval for the group mean $\mu_{1}$:


$\mu_{1} = 3.7457 \pm 2.059539 * \frac{\sqrt{0.0413708}}{\sqrt{7}} = 3.7457 \pm 0.1583317$, and so we can write that the 95% confidence interval for $\mu_{1}$ is $\mu_{1} \in (3.587368,3.904032)$.


## Problem 4
Mean diff = $\bar{y}_{k\cdot}-\bar{y}_{l\cdot}$:
```{r}
#tidyverse initalization hidden 
rats_sum <- rats %>% group_by(as.factor(diet)) %>% summarise(group_mean = mean(y))
for (x in 1:(nrow(rats_sum)-1)) {
  for (y in (x+1):nrow(rats_sum)) {
    print(rats_sum$group_mean[y]-rats_sum$group_mean[x])
  }
}
```
$\text{SE}(\bar{y}_{k\cdot}-\bar{y}_{l\cdot}) = \sqrt{\text{MSE}(\frac{1}{n_{k}}+\frac{1}{n_{l}})}$
```{r}
rats_count <- rats %>% count(as.factor(diet))
for (x in 1:(nrow(rats_count)-1)) {
  for (y in (x+1):nrow(rats_count)) {
    print(sqrt((0.0413708)*((1/rats_count$n[x])+(1/rats_count$n[y]))))
  }
}
```
$\text{t-stat} = \frac{\bar{y}_{k\cdot}-\bar{y}_{l\cdot}}{\sqrt{\text{MSE}(\frac{1}{n_{k}}+\frac{1}{n_{l}})}}$
```{r}
rat_comb <- left_join(rats_sum,rats_count,by = "as.factor(diet)")
for (x in 1:(nrow(rat_comb)-1)) {
  for (y in (x+1):nrow(rat_comb)) {
    print((rat_comb$group_mean[y]-rat_comb$group_mean[x])/(sqrt((0.0413708)*((1/rat_comb$n[x])+(1/rat_comb$n[y])))))
  }
}
```
Finding p-values ($\text{N-g}=29-4=25$):
```{r}
for (x in 1:(nrow(rat_comb)-1)) {
  for (y in (x+1):nrow(rat_comb)) {
    print(2*pt(abs
      (as.numeric((rat_comb$group_mean[y]-rat_comb$group_mean[x])/
        (sqrt(
          (0.0413708)*((1/rat_comb$n[x])+(1/rat_comb$n[y]))
              )
         ))),25,lower.tail = FALSE))
  }
}
```


diet pair | mean diff | Standard Error (SE) |  t-stat | p-value
:-----:|:--------:|:--------:|:--------:|:--------:
2-1  | -0.1657143  | 0.1052685  | -1.574205 | 0.1280115
3-1  | -0.147381  | 0.1131603  | -1.302409 | 0.2046479
4-1  | 0.1767857  | 0.1052685  | 1.679379 | 0.1055351
3-2  | 0.01833333  | 0.1098475  | 0.166898 | 0.8687929
4-2  | 0.3425  | 0.1016991  | 3.367779 | 0.002456
4-3  | 0.3241667  | 0.1098475  | 2.95106 | 0.006789461

4-2 and 4-3 are significant at the 5% significance level. 

Underline Diagram
```
  2      3       1      4
 3.58   3.60   3.75   3.92
-------------------
              ------------
```