---
title: "STAT 222 Spring 2021 HW5"
author: "Matthew Zhao"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
header-includes: \usepackage{pdfpages}
geometry: margin = .65in
fontsize: 12pt
---

```{r echo=F}
library(knitr)
knitr::opts_chunk$set(fig.width=4, fig.height=3.5, message=F, warning=F, collapse=T)
options(scipen=6, digits=5)
```


## Question 1

```{r}
insulate = read.table("http://www.stat.uchicago.edu/~yibi/s222/insulate.txt", h=T)
```


### Q1a --- 4 points

```{r}
m1 = lm(failtime~as.factor(material),data=insulate)
m2 = lm(log(failtime) ~ as.factor(material), data=insulate)
```


### Q1b --- 2 points


```{r}
library(emmeans)
summary(emmeans(m1, "material", level=0.95))
```

```{r}
summary(emmeans(m2, "material", level=0.95))
exp(summary(emmeans(m2, "material", level=0.95))[,5:6])
```


## Question 2

```{r}
logging = read.table("http://www.stat.uchicago.edu/~yibi/s222/logging.txt", h=T)
```


### Q2a --- 2 points


```{r, fig.width=3, fig.height=2.8, out.width='30%'}
library(ggplot2)
ggplot(logging, aes(x=condition, y=nitrate)) + geom_boxplot()
```

### Q2b --- 4 points


```{r}
logging$lognitrate = log(10+logging$nitrate)
lmlog = lm(lognitrate ~ condition, data=logging)
```


### Q2c --- 2 points

```{r,  fig.width=7, fig.height=2.5}
library(ggplot2)
ggplot(logging, aes(x=week, y=lmlog$res)) +
  geom_point() + geom_line() +
  facet_wrap(~condition, nrow=2)
```


### Q2d --- 2 points


```{r, fig.width=3, fig.height=3, fig.show='hold', out.width=c('35%', '35%')}
res.patch = subset(lmlog$res, logging$condition == "Patch-cut")
res.undisturb = subset(lmlog$res, logging$condition == "Undisturbed")
par(mai=c(.6,.6,.3,.01),mgp=c(2,.7,0))
plot(res.patch[1:87], res.patch[2:88], ylab="Current Residuals", 
      xlab="Lag 1 Residuals", main="Patch-Cut")
cor(res.patch[1:87], res.patch[2:88])

plot(res.undisturb[1:87], res.undisturb[2:88], ylab="Current Residuals", 
      xlab="Lag 1 Residuals", main="Undisturbed")
cor(res.undisturb[1:87], res.undisturb[2:88])
```

### Q2e --- 2 points



## Question 3


```{r fig.width=7.5, fig.height=4.3}
wheat56 = read.table("http://www.stat.uchicago.edu/~yibi/s222/wheat56.txt", h=T)
par(mai=c(.6,.6,.3,.1),mgp=c(2,.7,0))    # reducing the margin of plot
plot(wheat56$Longitude, wheat56$Latitude, type="n",
     xlab="Longitude", ylab="Latitude", main="Number on Each Plot = Wheat Variety ID")
for(i in 0:22){abline(v=i+0.5, lty=2)}   # adding the vertical grid lines
for(j in 0:11){abline(h=j+0.5, lty=2)}   # adding the horizontal grid lines
text(wheat56$Longitude, wheat56$Latitude, labels = wheat56$Variety, cex=0.75)
```

```{r}
lmwheat = lm(Yield ~ as.factor(Variety), data = wheat56)
```


### Q3a --- 2 points


```{r fig.width=8, fig.height=4.5}
par(mai=c(.6,.6,.3,.1),mgp=c(2,.7,0)) # reducing the margin of plot
plot(wheat56$Longitude, wheat56$Latitude, type="n", 
     xlab="Longitude", ylab="Latitude", main="Studentized Residual for Each Plot")
for(i in 0:22){abline(v=i+0.5, lty=2)} # adding the vertical grid lines
for(j in 0:11){abline(h=j+0.5, lty=2)} # adding the horizontal grid lines
text(wheat56$Longitude, wheat56$Latitude, 
     labels = round(rstudent(lmwheat),1), cex=0.75, 
     col = 1+(rstudent(lmwheat)>0))
```



### Q3b --- 1 point


```{r}
res.array = array(NA, dim = c(22,11))
for(i in 1:22){
  for(j in 1:11){
    if(sum(wheat56$Longitude == i & wheat56$Latitude == j)>0){
      res.array[i,j] = rstudent(lmwheat)[wheat56$Longitude == i & wheat56$Latitude == j]
    }
  }
}
round(res.array, digits=1)
```


```{r, fig.width=3, fig.height=2.6}
par(mai=c(.6,.6,.1,.1),mgp=c(2,.7,0))   # for reducing the margin of plots
plot(as.vector(res.array[1:21,1:11]),as.vector(res.array[2:22,1:11]), 
     xlab="e[i-1,j]", ylab="e[i,j]")
cor(as.vector(res.array[1:21,1:11]),as.vector(res.array[2:22,1:11]), 
    use="complete.obs")
```



### Q3c --- 3 points

